### ISSUE TITLE
Compare Patrick Chuong's work to javacef

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/swt-chromium#2]
Patrick Chuong offered an SWT-Chromium implementation in [April 2013](https://bugs.eclipse.org/bugs/show_bug.cgi?id=405031#c1), and renewed the offer in [June 2016](https://bugs.eclipse.org/bugs/show_bug.cgi?id=405031#c19).

It would be great to get Patrick's code out in the open, and see if his code or javacef's is a more promising starting point.

**Comment by nedtwigg** [comment]
To keep others up-to-date, I've started process with Patrick to get his code on GitHub.

**Comment by nedtwigg** [comment]
Hopefully we'll have Patrick's work in this repo before the end of the week.  Should have binaries of some form up not too long after that.

**Comment by nedtwigg** [comment]
We're evaluating the state of Patrick's work in #3.  Once we've got a handle on what it contains, we'll compare it to what we learn about JavaCEF in #1 and compare them here.

**Comment by nedtwigg** [comment]
|              | [JavaCEF](https://github.com/diffplug/swt-chromium/issues/1) | [ti_contribution](https://github.com/diffplug/swt-chromium/issues/3) |
|:------------ |:------------- |:-------------- |
| License | BSD (Jingyi Wei, independent) | EPL (Patrick Chuong, TI) |
| Platforms | win/mac/linux x86 & x86_64 | win/linux x86 |
| CEF3 Branch | 1750 (June 2014), 2526 (April 2016) | 1453 (October 2013) |
| Build | Uses gyp to generate projects per-platform | Manual |
| get/set zoom | :x: | :white_check_mark: |
| get/set url | :white_check_mark: | :white_check_mark: |
| set cookies | :white_check_mark: | :x: |
| back/forward/refresh/stop | :white_check_mark: | :white_check_mark: |
| progress tracking | :white_check_mark: | :white_check_mark: |
| popup tracking | :white_check_mark: | :white_check_mark: |
| context menus | :x: | :white_check_mark: |
| execute javascript in browser | :x: | :white_check_mark: |
| execute java in browser | :x: | :white_check_mark: |

Based on this, my gut feel is that JavaCEF is the best platform for getting the build to work, and from there we should either "swap" ti_contribution's code in, or at least use it to learn how to implement some of the features that JavaCEF is currently missing.

**Comment by pchuong** [comment]
When you upgrade to the latest CEF3. On Windows, you can use the binary download from the CEF3 repository. No build is required. I wasn't able to get Linux fully working back in the summer, it also doesn't require any manual build.  But I did use the gyp build script to build CEF3 to debug the issue on Linux. There are API change in CEF3, so you will need to make some adjustment to the native wrapper code.

**Comment by pchuong** [comment]
You can also set a port using Java property to enable remote debug Javascript. A very handy feature.

**Comment by nedtwigg** [comment]
Can you point us to the code for remote debug Javascript?

**Comment by RalfPetter** [comment]
I find this very interesting and think that it is way easier to extend on the TI contribution then to build on the JCEF Framwework. If this will really start i wll do my best to support this project.  I have good skills in SWT and Eclipse RCP development, but unforunatly i have only basic skills in JNI and C.

**Comment by RalfPetter** [comment]
I have tried this now and it looks really very cool. I think this could be a great alternative compared to the SWT browser widget. I think there are two things to do. Update CEF to the latest version and port this to 64 bit. I can provide development ressources for Windows.

**Comment by pchuong** [comment]
Ned, the code is in the N_Cef.cpp file, the option is passed from java to native C code. And the option is "-Dcef_remote_debugging_port=<port>", you can open an external chrome browser and enter localhost:<port> in the address bar.

**Comment by nedtwigg** [comment]
@RalfPetter Thanks!  Here's how I'm planning on proceeding, but feel free to explore another path too :)

- Setup a CI and build process for Patrick Chuong's existing CEF3 1453 branch
- Port to all 5 platforms 
- Then move to newer Chromium

**Comment by pchuong** [comment]
I would suggest you to get the latest CEF3 and migrate to the new API. I did that for windows back in the summer and it wasn't that much work. The build process to build the latest CEF3 is a lot better than what I have to do in the past.

**Comment by nedtwigg** [comment]
So, the code that you released is not based on CEF3?

**Comment by pchuong** [comment]
Is is based on CEF3, but building 1453 branch is pain in the butt in the past.

**Comment by nedtwigg** [comment]
Is there any chance we can get the windows code that you migrated?

**Comment by pchuong** [comment]
I was trying to recover it at the beginning of this week when I package the zip file, but I couldn't get it to run. I must have over written it with clearcase update while I work on another project. If I have more time, maybe I can try to recover it. But I am busy at the moment with other projects.

**Comment by nedtwigg** [comment]
Okay.  I'm working on a repeatable build process using the latest CEF3.  Maybe @RalfPetter can help migrate some of your code over to it when it's ready.

**Comment by RalfPetter** [comment]
I would suggest, that we concentrate on Windows in the beginning and go multiplatform later. If someone wants support for a specific plattform, he Can Support the work.

**Comment by RalfPetter** [comment]
Why do we need to compile cef3 for our self? There are already precompiled binaries for all plattform available that we can use. I think we should use them and concentrate on the SWT Wrapper and the JNI bindings.

**Comment by nedtwigg** [comment]
I need win/mac/linux 32/64.  If you get Windows further along than I'm able to get mac and linux, that's fine with me, but I will make sure that our build process supports all 5.  When I say "repeatable build process" I mean download the precompiled cef3 binaries, compile our jars, publish to p2, etc.

**Comment by RalfPetter** [comment]
I can help with Linux, but not with Mac.

**Comment by pchuong** [comment]
You will need to compile CEF3/Chromium and debug the code when things doesn't work :). For branch 1453, I have to compile it and make some changes due to bugs in CEF/Chromium.

**Comment by nedtwigg** [comment]
I just uploaded a build skeleton that downloads the latest SWT libs, and the latest CEF3 for each platform, and links them together into project files.  You can [read about it here](https://github.com/diffplug/swt-chromium/blob/master/CONTRIBUTING.md).

I tried to put some of Patrick's code into it, but I think I still don't understand how it works.  It looks to me that:

- you have a Java API
- you run javah to generate C header and source which matches that Java API
- you write glue C++ between the generated code and the chromium libs
- you compile the glue code into a shared library

Is this correct?

**Comment by RalfPetter** [comment]
Yes this is correct. I have never worked with gradle before, so I am not very happy with your decision, that your build process installs a whole ide. Why is it not possible to use my standard Eclipse IDE?. I have many plugins installed which i use regulary and i do not want to install them in this new IDE. With the branch of Patrick it was so easy. I have cloned the repository with EGIT and i can start hacking on his codebase immediatly.  If you prefer to use gradle to download cef3 and other dependencies you can use this from eclipse too. So i think there is no need to download an IDE.

http://www.vogella.com/tutorials/EclipseGradle/article.html

**Comment by nedtwigg** [comment]
@RalfPetter If you don't call `gradlew ide`, then it won't download the IDE - it's completely optional.  If you prefer to import it into eclipse yourself, just run `gradlew eclipse` and it will generate the eclipse project files for you to import.

I picked gradle because it's the one that I know best, and I know how all of its OSGi / p2 plugins work, and it has support for native builds as well.  It sounds like you understand what we need to do better than I do, If you prefer a different build system feel free to put in files for that!  But I think if the build is not fully automated so that `git clone; gradlew build` does't produce the full result from scratch, then it will be hard to collaborate as different people end up with different results on their local machines.

I won't be able to work on this much until ~Dec 1, so feel free to reorganize the project in a different direction if you prefer, and I'll follow along :)

**Comment by nedtwigg** [comment]
Closing in favor of #10
