### ISSUE TITLE
Evaluate Patrick Chuong's work (from TI)

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/swt-chromium#3]
Many thanks to Patrick Chuong and TI for their contribution of a working CEF embed.  It is available in the [ti_contribution](https://github.com/diffplug/swt-chromium/tree/ti_contribution) branch of this repo.  **Warning: this branch contains 178MB, mostly binaries!**  I've dumped it there just for now, we'll make sure that cloning the `master` branch stays light and clean.  If you'd like to take a look at it, clone this repo, checkout `ti_contribution`, then run `gradlew ide` and you can look at the source using JDT and CDT.

Here's a summary of the work as it stands (please correct me if I'm wrong, Patrick):

- CEF3 bindings for win32 and linux32 (not mac, not x64)
- Chromium version is 27.0.1453.110 (based on [`com.ti.chromium.browser/src_native/CHROMIUM_BUILD_COMPATIBILITY.txt`](https://github.com/diffplug/swt-chromium/blob/ti_contribution/com.ti.chromium.browser/src_native/CHROMIUM_BUILD_COMPATIBILITY.txt)), which is CEF3 branch 1453 from October 2013.
- Includes [scripts for generating JNI headers](https://github.com/diffplug/swt-chromium/tree/ti_contribution/com.ti.chromium.browser/jni_scripts).
- [`CefBrowser`](https://github.com/diffplug/swt-chromium/blob/ti_contribution/com.ti.chromium.browser/src/com/ti/chromium/browser/cef/CefBrowser.java) is an SWT Composite with the following API:
    + get/set zoom
    + get/set url, and listen for changes with `LocationListener`
    + back/forward/refresh/stop
    + run javascript in the browser (`boolean execute(String script) `, `Object evaluate(String script)`)
    + run java in the browser (`CefBrowserFunction`)
    + progress tracking with `ProgressListener`
    + listen for popups with `OpenWindowListener`
    + incomplete support for Context Menus (am I correct that they don't do anything yet?)

It also contains some non-SWT eclipse stuff (e.g. ChromiumBrowserView is a ViewPart).

This is the work needed to move forward:

- setup a build pipeline with `gclient` and `depot_tools` to allow easy CEF updating over time
- remove non-SWT dependencies (remove ChromiumBrowserView and embed json)
- add support for x64
- publish artifacts to p2

Can you review this Patrick, and let me know where I'm wrong or where there are better options?

**Comment by pchuong** [comment]
- The context menu should be working as well, we have been using it for our product
- And yes, you do need to setup glcient and depot_tools to pull the source and build when thing doesn't work.

**Comment by nedtwigg** [comment]
How does the context menu work?  Looking at the [code](https://github.com/diffplug/swt-chromium/blob/ti_contribution/com.ti.chromium.browser/src/com/ti/chromium/browser/cef/CefBrowserContextMenu.java), I only see these methods:

```java
CefBrowserContextMenu(CefBrowser browser, int id, String label)
void dispose()
abstract void widgetSelected(int detail);
```

So do you create a random ID, pick a string for the label, and then right-clicks will popup a menu with these labels?

**Comment by nedtwigg** [comment]
This work is compared to JavaCEF in #2.

**Comment by pchuong** [comment]
It is a simple SWT context menu.

		new CefBrowserContextMenu(browser, 1, "foobar") {
			@Override
			public void widgetSelected(int detail) {
				MessageDialog.openInformation(parent.getShell(), "foobar", "hello I am foobar!");
			}
		};

**Comment by nedtwigg** [comment]
Closing in favor of #10
