### ISSUE TITLE
Get paid to work on this / Pay to help make this happen

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/swt-chromium#6]
The eclipse foundation has raised money to build an officially-supported SWT Browser based on embedded Chromium.  It is [taking bids](https://projects.eclipse.org/development_effort/implement-swtchromium-integration) on the project from developers.  If you aren't able to develop the project yourself, you can still make a [directed donation](http://www.eclipse.org/contribute/dev_program.php) to the eclipse foundation which will go towards reviving the SWT Browser with a modern embedded Chromium.  It's called FEEP (Friends of Eclipse Enhancement Program).

Bids for this cycle are required by December 23, 2016.

Personally, I will not be submitting a bid, but will happily assist any bidders as a volunteer if they would like to continue down the path outlined in #5.

**Comment by nedtwigg** [comment]
At EclipseConverge 2017, I spoke with Eclipse staff.  There is heavy interest in making this happen.  If you are interesting in working on this project, we can probably get you funding outside of the FEEP schedule.  Shoot me an email and I can connect you to the pertinent folks in the Eclipse org.

**Comment by gzunino** [comment]
@nedtwigg I'm (http://www.wemaketechnology.com/) developing a (yet another) Chromium Widget for SWT based on CEF. It takes a different approach to the existing different framework approaches regarding native bindings and CEF, which simplifies maintenance and future CEF updates, by not using JNI nor C code and a a fully automated build.

This is part of a greater vision to provide a framework similar to Elektron for java. I'm initially open to open source the widget and also contributing to eclipse. My goal is to provide consulting and development services around the framework.

I think we may be able to mutually benefit in some way, given your interest on the subject (I have been following all your posts in related projects and forums). Feel free to contact me (guillez at gmail) if you are interested.

**Comment by nedtwigg** [comment]
Closing in favor of #10
